// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {

		int N = Integer.parseInt(args[0]);

		int countGreater = 0;
		int countLessEqual = 0;

		for (int i = 0; i < N; i++) {
			double result = Math.random();

		if (result > 0.5) {
		countGreater++;	
		} else {
			countLessEqual++; }
		}

		System.out.println("> 0.5:  " + countGreater + " times");
		System.out.println("<= 0.5: " + countLessEqual + " times");

		double ratio = ((double) countGreater / countLessEqual);

		if (countLessEqual != 0) {
			System.out.println("Ratio:  " + ratio);	
		}

	}
}
